name: Release

on:
  push:
    tags:
      - "v*"
      - "test-v*"

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: create build artifacts
        run: go build -o goproxy.exe main.go
        env:
          CGO_ENABLED: "0"
      - name: create zip
        run: |
          go build -o goproxy.exe main.go
          tar -a -c -f goproxy-${{ github.ref_name }}.zip goproxy.exe
      - uses: actions/upload-artifact@v3
        with:
          name: goproxy.zip
          path: goproxy-${{ github.ref_name }}.zip
          if-no-files-found: error
  release:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Download tar artifact
        uses: actions/download-artifact@v3
        with:
          name: goproxy.zip
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release create
          "${{ github.ref_name }}"
          goproxy-${{ github.ref_name }}.zip
          --draft
          --title "${{ github.ref_name }}"
          --repo ${{ github.repository }}
